services:
  - type: worker
    name: maythusharmusicvv2
    env: python
    plan: pro
    region: ohio
    buildCommand: pip3 install --no-cache-dir --upgrade --requirement requirements.txt
    startCommand: bash start
    envVars:
      - key: API_ID
        value: "23301178"
      - key: API_HASH
        value: "7387774d17aaa79c3744ff5d9d148214"
      - key: BOT_TOKEN
        value: "7882848304:AAH2S7suSy0X859zI-jvSAYvTGRPO4uqM40"
      - key: MONGO_DB_URI
        value: "mongodb+srv://pyaesonev1:pyaesone@pyaesonev1.4nssv9g.mongodb.net/?retryWrites=true&w=majority"
      - key: OWNER_ID
        value: "5821905026"
      - key: LOGGER_ID
        value: "-1001558698407"
      - key: STRING_SESSION
        value: "BQFjjDoAwtAyKFqn98l5rBTWMOYD7TOO9lq-rV2ssTECW1EE7xAavNCVHMGJuP5W6Cv-HNt38qdoA_JY35oellStB6aWwjyb5Px2O8K4RzttSTHhvjTWHNhvt85xefiMGuYqsV8aUNSvkIYbHeukZVdzdGTWjXKPafx8oIFML6AySKfJYtULe6ZPbSKllRHLnboatOeYSq7P187DLrMTI8xRANq61_ScSnA7pAkG4cf3vKgo0LkyKx63NN9QQDKzaTWvEY1GO8e0osDHbct745RY03fFEd9s6avS4oEtEOEt6N8xnh0BMwplynxfLhWAdaTXbuEv_IyJhdrtTQ8PlIMjFQ3x1AAAAAFsjYQzAA"
